name: Github-CI-Hotfix-Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

env:
  # secrets can be set in settings/secrets on github
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  deploy:
    # only run on staging branch
    name: deploy release
    runs-on: ubuntu-latest
    env:
      FROM_TAG_PREFIX: hotfix-github
      TO_TAG_PREFIX: release-github
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set target variable
        run: |
          target=$(git name-rev --refs="refs/remotes/origin/*" --name-only ${GITHUB_SHA})
          echo ::set-env name=TARGET::${target}
      - name: show env
        run: env
      - if: contains(env.TARGET, 'remotes/origin/hotfix_v')
        name: setup docker
        run: |
          sudo ./ci/github/helpers/setup_docker_compose.bash
          ./ci/github/helpers/setup_docker_experimental.bash
          ./ci/github/helpers/setup_docker_buildx.bash
          echo ::set-env name=DOCKER_BUILDX::1
      - if: contains(env.TARGET, 'remotes/origin/hotfix_v')
        name: set owner variable
        run: echo ::set-env name=OWNER::${GITHUB_REPOSITORY%/*}
      - if: contains(env.TARGET, 'remotes/origin/hotfix_v')
        name: set git tag
        run: echo ::set-env name=GIT_TAG::${GITHUB_REF##*/}
      - if: contains(env.TARGET, 'remotes/origin/hotfix_v')
        name: deploy
        run: ./ci/deploy/dockerhub-tag-version.bash
