name: Github-CI Push/PR

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
    paths-ignore:
      - "*.md"
      - "*.png"
      - "*.svg"
      - "docs/**"
      - ".vscode/**"
      - ".vscode-template/**"
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "*.md"
      - "*.png"
      - "*.svg"
      - "docs/**"
      - ".vscode/**"
      - ".vscode-template/**"

env:
  # secrets can be set in settings/secrets on github
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  CC_TEST_REPORTER_ID: 21a72eb30476c870140b1576258873a41be6692f71bd9aebe812174b7d8f4b4e
  #enable buildkit
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  build-test-images:
    # make PR faster by executing this one straight as PR cannot push to the registry anyway
    runs-on: ubuntu-20.04
    name: build docker test images
    steps:
      - uses: actions/checkout@v2
      - name: setup docker
        if: github.event_name == 'push'
        run: |
          sudo ./ci/github/helpers/setup_docker_compose.bash
          ./ci/github/helpers/setup_docker_experimental.bash
          ./ci/github/helpers/setup_docker_buildx.bash
          echo ::set-env name=DOCKER_BUILDX::1
      - name: show system environs
        if: github.event_name == 'push'
        run: ./ci/helpers/show_system_versions.bash
      - name: build images
        if: github.event_name == 'push'
        run: ./ci/build/test-images.bash build_images
      - name: set owner variable
        if: github.event_name == 'push'
        run: echo ::set-env name=OWNER::${GITHUB_REPOSITORY%/*}
      - name: push images
        # only pushes have access to the docker credentials
        if: github.event_name == 'push'
        run: ./ci/deploy/dockerhub-test-images.bash

  deploy:
    name: deploy to dockerhub
    if: github.event_name == 'push'
    needs: [build-test-images]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup docker
        run: |
          sudo ./ci/github/helpers/setup_docker_compose.bash
          ./ci/github/helpers/setup_docker_experimental.bash
          ./ci/github/helpers/setup_docker_buildx.bash
          echo ::set-env name=DOCKER_BUILDX::1
      - name: set owner variable
        run: echo ::set-env name=OWNER::${GITHUB_REPOSITORY%/*}
      - name: deploy master
        if: github.ref == 'refs/heads/master'
        env:
          TAG_PREFIX: master-github
        run: ./ci/deploy/dockerhub-deploy.bash
